create table system_params (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    value text not null,
    description text,
    data_type varchar(20) not null,
    system_defined boolean not null default false,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create index ix_system_params_name on system_params (name);
