create table system_param_types (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    description text,
    system_defined boolean not null default false,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create index ix_system_param_types_name on system_param_types (name);

insert into system_param_types (name, description, system_defined, created_at, updated_at)
values ('Khác', 'Các tham số chưa được phân loại', true, now(), now());

alter table system_params
    add column type_id bigint;

update system_params
set type_id = (select id from system_param_types where name = 'Khác');

alter table system_params
    alter column type_id set not null,
    add constraint fk_system_params_type
        foreign key (type_id) references system_param_types (id);

create index ix_system_params_type_id on system_params (type_id);

select setval(pg_get_serial_sequence('system_param_types', 'id'), (select max(id) from system_param_types));
