package com.nongthinh.agri_catalog_service.common.exception;

public enum ErrorCode {

    //AUTHENTICATION ERROR
    INVALID_TOKEN("AUTH_INVALID_TOKEN", "Invalid token", ErrorType.AUTHENTICATION),
    INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS", "Invalid credentials", ErrorType.AUTHENTICATION),
    INVALID_API_KEY("AUTH_INVALID_API_KEY", "Invalid API key", ErrorType.AUTHENTICATION),
    UNAUTHENTICATED("AUTH_UNAUTHENTICATED", "Unauthenticated", ErrorType.AUTHENTICATION),


    //AUTHORIZATION ERROR
    FORBIDDEN("AUTH_FORBIDDEN", "Forbidden", ErrorType.AUTHORIZATION),

    //INVALID KEY ERROR
    INVALID_KEY("AUTH_INVALID_KEY", "Invalid key", ErrorType.VALIDATION),

    //INTERNAL ERROR
    INTERNAL_ERROR("SYS_INTERNAL_ERROR", "Internal error", ErrorType.SYSTEM),

    //BUSINESS ERROR
    ROLES_REQUIRED("BUS_ROLES_REQUIRED", "Roles are required", ErrorType.BUSINESS_RULE),
    EMAIL_INVALID("BUS_EMAIL_INVALID", "Email is invalid", ErrorType.BUSINESS_RULE),
    EMAIL_FORMAT_INVALID("BUS_EMAIL_FORMAT_INVALID", "Email format is invalid", ErrorType.BUSINESS_RULE),
    FAILED_LOGIN_COUNT_INVALID("BUS_FAILED_LOGIN_COUNT_INVALID", "Failed login count is invalid", ErrorType.BUSINESS_RULE),
    ROLE_INVALID("BUS_ROLE_INVALID", "Role is invalid", ErrorType.BUSINESS_RULE),
    PERMISSION_INVALID("BUS_PERMISSION_INVALID", "Permission is invalid", ErrorType.BUSINESS_RULE),
    EMAIL_ALREADY_EXISTS("BUS_EMAIL_ALREADY_EXISTS", "Email already exists", ErrorType.BUSINESS_RULE),
    ROLE_CANNOT_BE_DELETED("BUS_ROLE_CANNOT_BE_DELETED", "Role cannot be deleted", ErrorType.BUSINESS_RULE),
    USER_DISABLED("BUS_USER_DISABLED", "User is disabled", ErrorType.BUSINESS_RULE),
    EMAIL_NOT_VERIFIED("BUS_EMAIL_NOT_VERIFIED", "Email is not verified", ErrorType.BUSINESS_RULE),
    SESSION_REVOKED("BUS_SESSION_REVOKED", "Session is revoked", ErrorType.BUSINESS_RULE),
    SESSION_REVOKED_REASON_REQUIRED("BUS_SESSION_REVOKED_REASON_REQUIRED", "Session revoked reason is required", ErrorType.BUSINESS_RULE),
    SESSION_INVALID("BUS_SESSION_INVALID", "Session is invalid", ErrorType.BUSINESS_RULE),
    SESSION_EXPIRES_AT_INVALID("BUS_SESSION_EXPIRES_AT_INVALID", "Session expires at is invalid", ErrorType.BUSINESS_RULE),
    USER_LOCKED("BUS_USER_LOCKED", "User is locked", ErrorType.BUSINESS_RULE),
    INVALID_AUTH_PROVIDER("BUS_INVALID_AUTH_PROVIDER", "Invalid auth provider for this operation", ErrorType.BUSINESS_RULE),

    
    //NOT FOUND ERROR
    ROLE_NOT_FOUND("NOT_FOUND_ROLE_NOT_FOUND", "Role not found", ErrorType.NOT_FOUND),
    USER_NOT_FOUND("NOT_FOUND_USER_NOT_FOUND", "User not found", ErrorType.NOT_FOUND),
    PERMISSION_NOT_FOUND("NOT_FOUND_PERMISSION_NOT_FOUND", "Permission not found", ErrorType.NOT_FOUND),
    SESSION_NOT_FOUND("NOT_FOUND_SESSION_NOT_FOUND", "Session not found", ErrorType.NOT_FOUND),
    PROFILE_NOT_FOUND("NOT_FOUND_PROFILE_NOT_FOUND", "Profile not found", ErrorType.NOT_FOUND),
    PRODUCT_CATEGORY_NOT_FOUND("NOT_FOUND_PRODUCT_CATEGORY_NOT_FOUND", "Product category not found", ErrorType.NOT_FOUND),
    PRODUCT_NOT_FOUND("NOT_FOUND_PRODUCT_NOT_FOUND", "Product not found", ErrorType.NOT_FOUND),
    PRODUCT_IMAGE_NOT_FOUND("NOT_FOUND_PRODUCT_IMAGE_NOT_FOUND", "Product image not found", ErrorType.NOT_FOUND),
    CROP_TYPE_NOT_FOUND("NOT_FOUND_CROP_TYPE_NOT_FOUND", "Crop type not found", ErrorType.NOT_FOUND),
    AI_MODEL_NOT_FOUND("NOT_FOUND_AI_MODEL_NOT_FOUND", "AI model not found", ErrorType.NOT_FOUND),
    AI_MODEL_VERSION_NOT_FOUND("NOT_FOUND_AI_MODEL_VERSION_NOT_FOUND", "AI model version not found", ErrorType.NOT_FOUND),
    AI_MODEL_DEPLOYMENT_NOT_FOUND("NOT_FOUND_AI_MODEL_DEPLOYMENT_NOT_FOUND", "AI model deployment not found", ErrorType.NOT_FOUND),
    AI_MODEL_DISEASE_MAPPING_NOT_FOUND("NOT_FOUND_AI_MODEL_DISEASE_MAPPING_NOT_FOUND", "AI model disease mapping not found", ErrorType.NOT_FOUND),
    DISEASE_NOT_FOUND("NOT_FOUND_DISEASE_NOT_FOUND", "Disease not found", ErrorType.NOT_FOUND),
    PRODUCT_DISEASE_TREATMENT_NOT_FOUND("NOT_FOUND_PRODUCT_DISEASE_TREATMENT_NOT_FOUND", "Product disease treatment not found", ErrorType.NOT_FOUND),
    FILE_NOT_FOUND("NOT_FOUND_FILE_NOT_FOUND", "File not found", ErrorType.NOT_FOUND),

    PRODUCT_CATEGORY_SLUG_ALREADY_EXISTS("BUS_PRODUCT_CATEGORY_SLUG_ALREADY_EXISTS", "Product category slug already exists", ErrorType.BUSINESS_RULE),
    PRODUCT_CATEGORY_PARENT_INVALID("BUS_PRODUCT_CATEGORY_PARENT_INVALID", "Product category cannot be its own parent", ErrorType.BUSINESS_RULE),
    PRODUCT_CATEGORY_HAS_CHILDREN("BUS_PRODUCT_CATEGORY_HAS_CHILDREN", "Product category has child categories", ErrorType.BUSINESS_RULE),
    CROP_TYPE_CODE_ALREADY_EXISTS("BUS_CROP_TYPE_CODE_ALREADY_EXISTS", "Crop type code already exists", ErrorType.BUSINESS_RULE),
    CROP_TYPE_IN_USE("BUS_CROP_TYPE_IN_USE", "Crop type is in use", ErrorType.BUSINESS_RULE),
    CROP_TYPE_INACTIVE("BUS_CROP_TYPE_INACTIVE", "Crop type is inactive", ErrorType.BUSINESS_RULE),
    AI_MODEL_CODE_ALREADY_EXISTS("BUS_AI_MODEL_CODE_ALREADY_EXISTS", "AI model code already exists", ErrorType.BUSINESS_RULE),
    AI_MODEL_CROP_COVERAGE_INVALID("BUS_AI_MODEL_CROP_COVERAGE_INVALID", "AI model crop coverage is invalid", ErrorType.BUSINESS_RULE),
    AI_MODEL_CROP_COVERAGE_IMMUTABLE("BUS_AI_MODEL_CROP_COVERAGE_IMMUTABLE", "AI model crop coverage cannot change after a version exists", ErrorType.BUSINESS_RULE),
    AI_MODEL_RETIRED("BUS_AI_MODEL_RETIRED", "Retired AI model cannot be changed", ErrorType.BUSINESS_RULE),
    AI_MODEL_VERSION_ALREADY_EXISTS("BUS_AI_MODEL_VERSION_ALREADY_EXISTS", "AI model version already exists", ErrorType.BUSINESS_RULE),
    AI_MODEL_VERSION_STATE_INVALID("BUS_AI_MODEL_VERSION_STATE_INVALID", "AI model version state does not allow this operation", ErrorType.BUSINESS_RULE),
    AI_MODEL_VERSION_MANIFEST_INVALID("BUS_AI_MODEL_VERSION_MANIFEST_INVALID", "AI model version class manifest is invalid", ErrorType.BUSINESS_RULE),
    AI_MODEL_VERSION_ARTIFACT_INVALID("BUS_AI_MODEL_VERSION_ARTIFACT_INVALID", "AI model version artifact is invalid", ErrorType.BUSINESS_RULE),
    AI_MODEL_VERSION_MAPPING_NOT_READY("BUS_AI_MODEL_VERSION_MAPPING_NOT_READY", "AI model version disease mappings are not ready", ErrorType.BUSINESS_RULE),
    AI_MODEL_DISEASE_MAPPING_ALREADY_EXISTS("BUS_AI_MODEL_DISEASE_MAPPING_ALREADY_EXISTS", "AI model disease mapping already exists for this class and crop", ErrorType.BUSINESS_RULE),
    AI_MODEL_DISEASE_MAPPING_CLASS_INVALID("BUS_AI_MODEL_DISEASE_MAPPING_CLASS_INVALID", "Only DISEASE model classes can be mapped", ErrorType.BUSINESS_RULE),
    AI_MODEL_DISEASE_MAPPING_DISEASE_INVALID("BUS_AI_MODEL_DISEASE_MAPPING_DISEASE_INVALID", "Mapped disease must be approved and belong to the selected crop", ErrorType.BUSINESS_RULE),
    AI_MODEL_VERSION_HAS_ACTIVE_DEPLOYMENT("BUS_AI_MODEL_VERSION_HAS_ACTIVE_DEPLOYMENT", "AI model version has an active deployment", ErrorType.BUSINESS_RULE),
    AI_MODEL_DEPLOYMENT_SCOPE_INVALID("BUS_AI_MODEL_DEPLOYMENT_SCOPE_INVALID", "AI model deployment scope is invalid", ErrorType.BUSINESS_RULE),
    AI_MODEL_DEPLOYMENT_CROP_COVERAGE_INVALID("BUS_AI_MODEL_DEPLOYMENT_CROP_COVERAGE_INVALID", "AI model deployment is outside model crop coverage", ErrorType.BUSINESS_RULE),
    AI_MODEL_DEPLOYMENT_PRIORITY_CONFLICT("BUS_AI_MODEL_DEPLOYMENT_PRIORITY_CONFLICT", "An active deployment already uses this scope, crop, and priority", ErrorType.BUSINESS_RULE),
    AI_MODEL_DEPLOYMENT_STATE_INVALID("BUS_AI_MODEL_DEPLOYMENT_STATE_INVALID", "AI model deployment state does not allow this operation", ErrorType.BUSINESS_RULE),
    PRODUCT_SLUG_ALREADY_EXISTS("BUS_PRODUCT_SLUG_ALREADY_EXISTS", "Product slug already exists for this brand", ErrorType.BUSINESS_RULE),
    PRODUCT_LOCKED("BUS_PRODUCT_LOCKED", "Locked product publication status cannot be changed", ErrorType.BUSINESS_RULE),
    PRODUCT_PUBLICATION_STATUS_INVALID("BUS_PRODUCT_PUBLICATION_STATUS_INVALID", "Product publication status is invalid", ErrorType.BUSINESS_RULE),
    PRODUCT_IMAGE_FILE_ALREADY_USED("BUS_PRODUCT_IMAGE_FILE_ALREADY_USED", "File is already attached to a product image", ErrorType.BUSINESS_RULE),
    PRODUCT_IMAGE_FILE_INVALID("BUS_PRODUCT_IMAGE_FILE_INVALID", "File is not a valid product image", ErrorType.BUSINESS_RULE),
    DISEASE_SLUG_ALREADY_EXISTS("BUS_DISEASE_SLUG_ALREADY_EXISTS", "Disease slug already exists for this crop type", ErrorType.BUSINESS_RULE),
    DISEASE_STATUS_TRANSITION_INVALID("BUS_DISEASE_STATUS_TRANSITION_INVALID", "Disease status transition is invalid", ErrorType.BUSINESS_RULE),
    DISEASE_NOT_APPROVED("BUS_DISEASE_NOT_APPROVED", "Disease must be approved before it can be linked to a product", ErrorType.BUSINESS_RULE),
    PRODUCT_DISEASE_TREATMENT_ALREADY_EXISTS("BUS_PRODUCT_DISEASE_TREATMENT_ALREADY_EXISTS", "Product disease treatment already exists", ErrorType.BUSINESS_RULE),
    BRAND_RESOURCE_ACCESS_DENIED("AUTH_BRAND_RESOURCE_ACCESS_DENIED", "Brand cannot access another brand resource", ErrorType.AUTHORIZATION),

    //SYSTEM ERROR
    MAX_FAILED_LOGIN_COUNT_INVALID("SYS_MAX_FAILED_LOGIN_COUNT_INVALID", "Max failed login count is invalid", ErrorType.SYSTEM),
    FAILED_LOGIN_LOCKOUT_DURATION_INVALID("SYS_FAILED_LOGIN_LOCKOUT_DURATION_INVALID", "Failed login lockout duration is invalid", ErrorType.SYSTEM),
    
    //INFRASTRUCTURE ERROR
    REFRESH_TOKEN_UNSUCCESSFUL("INF_REFRESH_TOKEN_UNSUCCESSFUL", "Refresh token unsuccessful", ErrorType.INFRASTRUCTURE),
    EVENT_SERIALIZATION_FAILED("INF_EVENT_SERIALIZATION_FAILED", "Failed to serialize event", ErrorType.INFRASTRUCTURE),
    KEYCLOAK_USER_ID_NOT_FOUND("INF_KEYCLOAK_USER_ID_NOT_FOUND", "Keycloak user ID not found", ErrorType.INFRASTRUCTURE),
    KEYCLOAK_USER_CREATION_FAILED("INF_KEYCLOAK_USER_CREATION_FAILED", "Failed to create Keycloak user account", ErrorType.INFRASTRUCTURE),
    KEYCLOAK_EXCHANGE_CLIENT_TOKEN_FAILED("INF_KEYCLOAK_EXCHANGE_CLIENT_TOKEN_FAILED", "Failed to exchange keycloak client token", ErrorType.INFRASTRUCTURE),
    KEYCLOAK_LOGOUT_FAILED("INF_KEYCLOAK_LOGOUT_FAILED", "Failed to logout user account", ErrorType.INFRASTRUCTURE),
    KEYCLOAK_GET_ROLE_BY_NAME_FAILED("INF_KEYCLOAK_GET_ROLE_BY_NAME_FAILED", "Failed to get role by name", ErrorType.INFRASTRUCTURE),
    KEYCLOAK_ROLE_MAPPING_FAILED("INF_KEYCLOAK_ROLE_MAPPING_FAILED", "Failed to map role", ErrorType.INFRASTRUCTURE),
    FILE_SERVICE_UNAVAILABLE("INF_FILE_SERVICE_UNAVAILABLE", "File service is unavailable", ErrorType.INFRASTRUCTURE),
    MODEL_VALIDATION_UNAVAILABLE("INF_MODEL_VALIDATION_UNAVAILABLE", "Model validation service is unavailable", ErrorType.INFRASTRUCTURE),
    MODEL_RUNTIME_NOT_READY("SYS_MODEL_NOT_READY", "Model runtime is not ready", ErrorType.SERVICE_UNAVAILABLE),
    CATALOG_MAPPING_NOT_READY("SYS_CATALOG_MAPPING_NOT_READY", "Disease catalog mapping is not ready", ErrorType.SERVICE_UNAVAILABLE),
    MODEL_NOT_AVAILABLE_FOR_CROP("MODEL_NOT_AVAILABLE_FOR_CROP", "No active model is available for this crop", ErrorType.SERVICE_UNAVAILABLE),
    PROFILE_SERVICE_GET_FARMER_PROFILE_FAILED("INF_PROFILE_SERVICE_GET_FARMER_PROFILE_FAILED", "Failed to get farmer profile", ErrorType.INFRASTRUCTURE),
    PROFILE_SERVICE_GET_BRAND_PROFILE_FAILED("INF_PROFILE_SERVICE_GET_BRAND_PROFILE_FAILED", "Failed to get brand profile", ErrorType.INFRASTRUCTURE),
    PROFILE_SERVICE_GET_ADMIN_PROFILE_FAILED("INF_PROFILE_SERVICE_GET_ADMIN_PROFILE_FAILED", "Failed to get admin profile", ErrorType.INFRASTRUCTURE),
    KAFKA_PUBLISH_FAILED("INF_KAFKA_PUBLISH_FAILED", "Failed to publish event", ErrorType.INFRASTRUCTURE),
    
    //VALIDATION ERROR
    PASSWORD_REQUIRED("VAL_PASSWORD_REQUIRED", "Password is required", ErrorType.VALIDATION),
    EMAIL_REQUEST_FORMAT_INVALID("VAL_EMAIL_FORMAT_INVALID", "Email format is invalid", ErrorType.VALIDATION),
    TEMPORARY_REQUIRED("VAL_TEMPORARY_REQUIRED", "Temporary is required", ErrorType.VALIDATION),
    ENABLED_REQUIRED("VAL_ENABLED_REQUIRED", "Enabled is required", ErrorType.VALIDATION),
    FIRST_NAME_REQUIRED("VAL_FIRST_NAME_REQUIRED", "First name is required", ErrorType.VALIDATION),
    LAST_NAME_REQUIRED("VAL_LAST_NAME_REQUIRED", "Last name is required", ErrorType.VALIDATION),
    FIRST_NAME_LENGTH_INVALID("VAL_FIRST_NAME_LENGTH_INVALID", "First name must be between 1 and 255 characters", ErrorType.VALIDATION),
    LAST_NAME_LENGTH_INVALID("VAL_LAST_NAME_LENGTH_INVALID", "Last name must be between 3 and 255 characters", ErrorType.VALIDATION),
    GENDER_REQUIRED("VAL_GENDER_REQUIRED", "Gender is required", ErrorType.VALIDATION),
    GENDER_INVALID("VAL_GENDER_INVALID", "Gender is invalid", ErrorType.VALIDATION),
    PHONE_REQUIRED("VAL_PHONE_REQUIRED", "Phone is required", ErrorType.VALIDATION),
    PHONE_INVALID("VAL_PHONE_INVALID", "Phone is invalid", ErrorType.VALIDATION),
    PROVINCE_ID_INVALID("VAL_PROVINCE_ID_INVALID", "Province ID is invalid", ErrorType.VALIDATION),
    ADDRESS_DETAIL_TOO_LONG("VAL_ADDRESS_DETAIL_TOO_LONG", "Address detail must not exceed 500 characters", ErrorType.VALIDATION),
    AVATAR_URL_INVALID("VAL_AVATAR_URL_INVALID", "Avatar URL is invalid", ErrorType.VALIDATION),
    OTP_LENGTH_INVALID("VAL_OTP_LENGTH_INVALID", "OTP length is invalid", ErrorType.VALIDATION),
    OTP_REQUIRED("VAL_OTP_REQUIRED", "OTP is required", ErrorType.VALIDATION),
    PRODUCT_CATEGORY_NAME_REQUIRED("VAL_PRODUCT_CATEGORY_NAME_REQUIRED", "Product category name is required", ErrorType.VALIDATION),
    PRODUCT_CATEGORY_NAME_TOO_LONG("VAL_PRODUCT_CATEGORY_NAME_TOO_LONG", "Product category name must not exceed 150 characters", ErrorType.VALIDATION),
    PRODUCT_CATEGORY_SLUG_REQUIRED("VAL_PRODUCT_CATEGORY_SLUG_REQUIRED", "Product category slug is required", ErrorType.VALIDATION),
    PRODUCT_CATEGORY_SLUG_TOO_LONG("VAL_PRODUCT_CATEGORY_SLUG_TOO_LONG", "Product category slug must not exceed 180 characters", ErrorType.VALIDATION),
    PRODUCT_CATEGORY_DESCRIPTION_TOO_LONG("VAL_PRODUCT_CATEGORY_DESCRIPTION_TOO_LONG", "Product category description must not exceed 10000 characters", ErrorType.VALIDATION),
    PRODUCT_CATEGORY_DISPLAY_ORDER_INVALID("VAL_PRODUCT_CATEGORY_DISPLAY_ORDER_INVALID", "Product category display order must not be negative", ErrorType.VALIDATION),
    PRODUCT_CATEGORY_ACTIVE_REQUIRED("VAL_PRODUCT_CATEGORY_ACTIVE_REQUIRED", "Product category active status is required", ErrorType.VALIDATION),
    CROP_TYPE_CODE_REQUIRED("VAL_CROP_TYPE_CODE_REQUIRED", "Crop type code is required", ErrorType.VALIDATION),
    CROP_TYPE_CODE_TOO_LONG("VAL_CROP_TYPE_CODE_TOO_LONG", "Crop type code must not exceed 100 characters", ErrorType.VALIDATION),
    CROP_TYPE_CODE_INVALID("VAL_CROP_TYPE_CODE_INVALID", "Crop type code must use uppercase letters, digits, or underscores", ErrorType.VALIDATION),
    CROP_TYPE_NAME_REQUIRED("VAL_CROP_TYPE_NAME_REQUIRED", "Crop type name is required", ErrorType.VALIDATION),
    CROP_TYPE_NAME_TOO_LONG("VAL_CROP_TYPE_NAME_TOO_LONG", "Crop type name must not exceed 150 characters", ErrorType.VALIDATION),
    CROP_TYPE_DESCRIPTION_TOO_LONG("VAL_CROP_TYPE_DESCRIPTION_TOO_LONG", "Crop type description must not exceed 10000 characters", ErrorType.VALIDATION),
    CROP_TYPE_ACTIVE_REQUIRED("VAL_CROP_TYPE_ACTIVE_REQUIRED", "Crop type active status is required", ErrorType.VALIDATION),
    AI_MODEL_CODE_REQUIRED("VAL_AI_MODEL_CODE_REQUIRED", "AI model code is required", ErrorType.VALIDATION),
    AI_MODEL_CODE_TOO_LONG("VAL_AI_MODEL_CODE_TOO_LONG", "AI model code must not exceed 100 characters", ErrorType.VALIDATION),
    AI_MODEL_CODE_INVALID("VAL_AI_MODEL_CODE_INVALID", "AI model code must use uppercase letters, digits, or underscores", ErrorType.VALIDATION),
    AI_MODEL_NAME_REQUIRED("VAL_AI_MODEL_NAME_REQUIRED", "AI model name is required", ErrorType.VALIDATION),
    AI_MODEL_NAME_TOO_LONG("VAL_AI_MODEL_NAME_TOO_LONG", "AI model name must not exceed 255 characters", ErrorType.VALIDATION),
    AI_MODEL_DESCRIPTION_TOO_LONG("VAL_AI_MODEL_DESCRIPTION_TOO_LONG", "AI model description must not exceed 10000 characters", ErrorType.VALIDATION),
    AI_MODEL_TASK_TYPE_REQUIRED("VAL_AI_MODEL_TASK_TYPE_REQUIRED", "AI model task type is required", ErrorType.VALIDATION),
    AI_MODEL_CROP_COVERAGE_TYPE_REQUIRED("VAL_AI_MODEL_CROP_COVERAGE_TYPE_REQUIRED", "AI model crop coverage type is required", ErrorType.VALIDATION),
    AI_MODEL_CROP_TYPE_IDS_REQUIRED("VAL_AI_MODEL_CROP_TYPE_IDS_REQUIRED", "AI model crop type IDs are required", ErrorType.VALIDATION),
    AI_MODEL_VERSION_REQUIRED("VAL_AI_MODEL_VERSION_REQUIRED", "AI model version is required", ErrorType.VALIDATION),
    AI_MODEL_VERSION_TOO_LONG("VAL_AI_MODEL_VERSION_TOO_LONG", "AI model version must not exceed 128 characters", ErrorType.VALIDATION),
    AI_MODEL_VERSION_ARTIFACT_FILE_ID_REQUIRED("VAL_AI_MODEL_VERSION_ARTIFACT_FILE_ID_REQUIRED", "AI model version artifact file ID is required", ErrorType.VALIDATION),
    AI_MODEL_VERSION_ARTIFACT_SHA256_REQUIRED("VAL_AI_MODEL_VERSION_ARTIFACT_SHA256_REQUIRED", "AI model version artifact SHA-256 is required", ErrorType.VALIDATION),
    AI_MODEL_VERSION_ARTIFACT_SHA256_INVALID("VAL_AI_MODEL_VERSION_ARTIFACT_SHA256_INVALID", "AI model version artifact SHA-256 must be a 64 character hexadecimal value", ErrorType.VALIDATION),
    AI_MODEL_VERSION_INPUT_WIDTH_INVALID("VAL_AI_MODEL_VERSION_INPUT_WIDTH_INVALID", "AI model version input width must be positive", ErrorType.VALIDATION),
    AI_MODEL_VERSION_INPUT_HEIGHT_INVALID("VAL_AI_MODEL_VERSION_INPUT_HEIGHT_INVALID", "AI model version input height must be positive", ErrorType.VALIDATION),
    AI_MODEL_VERSION_CLASSES_REQUIRED("VAL_AI_MODEL_VERSION_CLASSES_REQUIRED", "AI model version classes are required", ErrorType.VALIDATION),
    AI_MODEL_VERSION_CLASS_INDEX_INVALID("VAL_AI_MODEL_VERSION_CLASS_INDEX_INVALID", "AI model version class index must not be negative", ErrorType.VALIDATION),
    AI_MODEL_VERSION_CLASS_CODE_REQUIRED("VAL_AI_MODEL_VERSION_CLASS_CODE_REQUIRED", "AI model version class code is required", ErrorType.VALIDATION),
    AI_MODEL_VERSION_CLASS_CODE_TOO_LONG("VAL_AI_MODEL_VERSION_CLASS_CODE_TOO_LONG", "AI model version class code must not exceed 100 characters", ErrorType.VALIDATION),
    AI_MODEL_VERSION_CLASS_DISPLAY_NAME_REQUIRED("VAL_AI_MODEL_VERSION_CLASS_DISPLAY_NAME_REQUIRED", "AI model version class display name is required", ErrorType.VALIDATION),
    AI_MODEL_VERSION_CLASS_DISPLAY_NAME_TOO_LONG("VAL_AI_MODEL_VERSION_CLASS_DISPLAY_NAME_TOO_LONG", "AI model version class display name must not exceed 255 characters", ErrorType.VALIDATION),
    AI_MODEL_VERSION_CLASS_KIND_REQUIRED("VAL_AI_MODEL_VERSION_CLASS_KIND_REQUIRED", "AI model version class kind is required", ErrorType.VALIDATION),
    AI_MODEL_DEPLOYMENT_MODEL_VERSION_ID_REQUIRED("VAL_AI_MODEL_DEPLOYMENT_MODEL_VERSION_ID_REQUIRED", "AI model deployment version ID is required", ErrorType.VALIDATION),
    AI_MODEL_DEPLOYMENT_SCOPE_REQUIRED("VAL_AI_MODEL_DEPLOYMENT_SCOPE_REQUIRED", "AI model deployment scope is required", ErrorType.VALIDATION),
    AI_MODEL_DEPLOYMENT_PRIORITY_INVALID("VAL_AI_MODEL_DEPLOYMENT_PRIORITY_INVALID", "AI model deployment priority must not be negative", ErrorType.VALIDATION),
    AI_MODEL_DISEASE_MAPPING_MODEL_VERSION_CLASS_ID_REQUIRED("VAL_AI_MODEL_DISEASE_MAPPING_MODEL_VERSION_CLASS_ID_REQUIRED", "AI model version class ID is required", ErrorType.VALIDATION),
    AI_MODEL_DISEASE_MAPPING_CROP_TYPE_ID_REQUIRED("VAL_AI_MODEL_DISEASE_MAPPING_CROP_TYPE_ID_REQUIRED", "Crop type ID is required", ErrorType.VALIDATION),
    AI_MODEL_DISEASE_MAPPING_DISEASE_ID_REQUIRED("VAL_AI_MODEL_DISEASE_MAPPING_DISEASE_ID_REQUIRED", "Disease ID is required", ErrorType.VALIDATION),
    PRODUCT_BRAND_ID_REQUIRED("VAL_PRODUCT_BRAND_ID_REQUIRED", "Product brand ID is required", ErrorType.VALIDATION),
    PRODUCT_CATEGORY_ID_REQUIRED("VAL_PRODUCT_CATEGORY_ID_REQUIRED", "Product category ID is required", ErrorType.VALIDATION),
    PRODUCT_NAME_REQUIRED("VAL_PRODUCT_NAME_REQUIRED", "Product name is required", ErrorType.VALIDATION),
    PRODUCT_NAME_TOO_LONG("VAL_PRODUCT_NAME_TOO_LONG", "Product name must not exceed 255 characters", ErrorType.VALIDATION),
    PRODUCT_SLUG_REQUIRED("VAL_PRODUCT_SLUG_REQUIRED", "Product slug is required", ErrorType.VALIDATION),
    PRODUCT_SLUG_TOO_LONG("VAL_PRODUCT_SLUG_TOO_LONG", "Product slug must not exceed 280 characters", ErrorType.VALIDATION),
    PRODUCT_SKU_TOO_LONG("VAL_PRODUCT_SKU_TOO_LONG", "Product SKU must not exceed 100 characters", ErrorType.VALIDATION),
    PRODUCT_REGISTRATION_NUMBER_TOO_LONG("VAL_PRODUCT_REGISTRATION_NUMBER_TOO_LONG", "Product registration number must not exceed 100 characters", ErrorType.VALIDATION),
    PRODUCT_MANUFACTURER_NAME_TOO_LONG("VAL_PRODUCT_MANUFACTURER_NAME_TOO_LONG", "Product manufacturer name must not exceed 255 characters", ErrorType.VALIDATION),
    PRODUCT_ORIGIN_COUNTRY_TOO_LONG("VAL_PRODUCT_ORIGIN_COUNTRY_TOO_LONG", "Product origin country must not exceed 100 characters", ErrorType.VALIDATION),
    PRODUCT_SHORT_DESCRIPTION_TOO_LONG("VAL_PRODUCT_SHORT_DESCRIPTION_TOO_LONG", "Product short description must not exceed 500 characters", ErrorType.VALIDATION),
    PRODUCT_FORM_TOO_LONG("VAL_PRODUCT_FORM_TOO_LONG", "Product form must not exceed 100 characters", ErrorType.VALIDATION),
    PRODUCT_UNIT_TOO_LONG("VAL_PRODUCT_UNIT_TOO_LONG", "Product unit must not exceed 50 characters", ErrorType.VALIDATION),
    PRODUCT_PACKAGE_SPECIFICATION_TOO_LONG("VAL_PRODUCT_PACKAGE_SPECIFICATION_TOO_LONG", "Product package specification must not exceed 255 characters", ErrorType.VALIDATION),
    PRODUCT_IMAGE_FILE_ID_REQUIRED("VAL_PRODUCT_IMAGE_FILE_ID_REQUIRED", "Product image file ID is required", ErrorType.VALIDATION),
    PRODUCT_IMAGE_ALT_TEXT_TOO_LONG("VAL_PRODUCT_IMAGE_ALT_TEXT_TOO_LONG", "Product image alt text must not exceed 255 characters", ErrorType.VALIDATION),
    PRODUCT_IMAGE_DISPLAY_ORDER_INVALID("VAL_PRODUCT_IMAGE_DISPLAY_ORDER_INVALID", "Product image display order must not be negative", ErrorType.VALIDATION),
    PRODUCT_IMAGE_PRIMARY_REQUIRED("VAL_PRODUCT_IMAGE_PRIMARY_REQUIRED", "Product image primary flag is required", ErrorType.VALIDATION),
    DISEASE_NAME_REQUIRED("VAL_DISEASE_NAME_REQUIRED", "Disease name is required", ErrorType.VALIDATION),
    DISEASE_NAME_TOO_LONG("VAL_DISEASE_NAME_TOO_LONG", "Disease name must not exceed 255 characters", ErrorType.VALIDATION),
    DISEASE_SLUG_REQUIRED("VAL_DISEASE_SLUG_REQUIRED", "Disease slug is required", ErrorType.VALIDATION),
    DISEASE_SLUG_TOO_LONG("VAL_DISEASE_SLUG_TOO_LONG", "Disease slug must not exceed 280 characters", ErrorType.VALIDATION),
    DISEASE_SCIENTIFIC_NAME_TOO_LONG("VAL_DISEASE_SCIENTIFIC_NAME_TOO_LONG", "Disease scientific name must not exceed 255 characters", ErrorType.VALIDATION),
    DISEASE_CROP_TYPE_REQUIRED("VAL_DISEASE_CROP_TYPE_REQUIRED", "Disease crop type is required", ErrorType.VALIDATION),
    DISEASE_CROP_TYPE_ID_REQUIRED("VAL_DISEASE_CROP_TYPE_ID_REQUIRED", "Disease crop type ID is required", ErrorType.VALIDATION),
    DISEASE_CROP_TYPE_TOO_LONG("VAL_DISEASE_CROP_TYPE_TOO_LONG", "Disease crop type must not exceed 100 characters", ErrorType.VALIDATION),
    DISEASE_AFFECTED_PART_TOO_LONG("VAL_DISEASE_AFFECTED_PART_TOO_LONG", "Disease affected part must not exceed 100 characters", ErrorType.VALIDATION),
    DISEASE_PATHOGEN_TYPE_TOO_LONG("VAL_DISEASE_PATHOGEN_TYPE_TOO_LONG", "Disease pathogen type must not exceed 50 characters", ErrorType.VALIDATION),
    DISEASE_SHORT_DESCRIPTION_TOO_LONG("VAL_DISEASE_SHORT_DESCRIPTION_TOO_LONG", "Disease short description must not exceed 500 characters", ErrorType.VALIDATION),
    DISEASE_THUMBNAIL_URL_TOO_LONG("VAL_DISEASE_THUMBNAIL_URL_TOO_LONG", "Disease thumbnail URL must not exceed 2000 characters", ErrorType.VALIDATION),
    DISEASE_REJECTION_REASON_REQUIRED("VAL_DISEASE_REJECTION_REASON_REQUIRED", "Disease rejection reason is required", ErrorType.VALIDATION),
    DISEASE_REJECTION_REASON_TOO_LONG("VAL_DISEASE_REJECTION_REASON_TOO_LONG", "Disease rejection reason must not exceed 2000 characters", ErrorType.VALIDATION),
    PRODUCT_DISEASE_TREATMENT_DISEASE_ID_REQUIRED("VAL_PRODUCT_DISEASE_TREATMENT_DISEASE_ID_REQUIRED", "Disease ID is required", ErrorType.VALIDATION),
    PRODUCT_DISEASE_TREATMENT_EFFECTIVENESS_LEVEL_INVALID("VAL_PRODUCT_DISEASE_TREATMENT_EFFECTIVENESS_LEVEL_INVALID", "Effectiveness level is invalid", ErrorType.VALIDATION),
    PRODUCT_DISEASE_TREATMENT_PRIORITY_INVALID("VAL_PRODUCT_DISEASE_TREATMENT_PRIORITY_INVALID", "Treatment priority must not be negative", ErrorType.VALIDATION),
    PRODUCT_DISEASE_TREATMENT_DOSAGE_TOO_LONG("VAL_PRODUCT_DISEASE_TREATMENT_DOSAGE_TOO_LONG", "Treatment dosage must not exceed 255 characters", ErrorType.VALIDATION),
    PRODUCT_DISEASE_TREATMENT_FREQUENCY_TOO_LONG("VAL_PRODUCT_DISEASE_TREATMENT_FREQUENCY_TOO_LONG", "Treatment frequency instruction must not exceed 255 characters", ErrorType.VALIDATION),
    INVALID_REQUEST_PARAMETER("VAL_INVALID_REQUEST_PARAMETER", "Request parameter or body value is invalid", ErrorType.VALIDATION),

    OTP_INVALID("BUS_OTP_INVALID", "OTP is invalid", ErrorType.BUSINESS_RULE),
    OTP_EXPIRED("BUS_OTP_EXPIRED", "OTP has expired", ErrorType.BUSINESS_RULE),
    OTP_ATTEMPT_LIMIT_EXCEEDED("BUS_OTP_ATTEMPT_LIMIT_EXCEEDED", "OTP attempt limit exceeded", ErrorType.BUSINESS_RULE),
    OTP_RESEND_TOO_FREQUENT("BUS_OTP_RESEND_TOO_FREQUENT", "OTP resend is too frequent", ErrorType.BUSINESS_RULE),
    OTP_RESEND_LIMIT_EXCEEDED("BUS_OTP_RESEND_LIMIT_EXCEEDED", "OTP resend limit exceeded", ErrorType.BUSINESS_RULE),
    EMAIL_ALREADY_VERIFIED("BUS_EMAIL_ALREADY_VERIFIED", "Email is already verified", ErrorType.BUSINESS_RULE),
    ADMIN_GROUP_REQUIRED("VAL_ADMIN_GROUP_REQUIRED", "Admin group is required", ErrorType.VALIDATION),
    ADMIN_GROUP_INVALID("VAL_ADMIN_GROUP_INVALID", "Admin group is invalid", ErrorType.VALIDATION),
    BRAND_NAME_REQUIRED("VAL_BRAND_NAME_REQUIRED", "Brand name is required", ErrorType.VALIDATION),
    BRAND_NAME_LENGTH_INVALID("VAL_BRAND_NAME_LENGTH_INVALID", "Brand name must be between {min} and {max} characters", ErrorType.VALIDATION),
    TAX_CODE_TOO_LONG("VAL_TAX_CODE_TOO_LONG", "Tax code must not exceed 20 characters", ErrorType.VALIDATION),
    DESCRIPTION_TOO_LONG("VAL_DESCRIPTION_TOO_LONG", "Description must not exceed 1000 characters", ErrorType.VALIDATION),
    REPRESENTATIVE_NAME_REQUIRED("VAL_REPRESENTATIVE_NAME_REQUIRED", "Representative name is required", ErrorType.VALIDATION),
    REPRESENTATIVE_PHONE_REQUIRED("VAL_REPRESENTATIVE_PHONE_REQUIRED", "Representative phone is required", ErrorType.VALIDATION),
    REPRESENTATIVE_EMAIL_REQUIRED("VAL_REPRESENTATIVE_EMAIL_REQUIRED", "Representative email is required", ErrorType.VALIDATION),
    REPRESENTATIVE_EMAIL_INVALID("VAL_REPRESENTATIVE_EMAIL_INVALID", "Representative email is invalid", ErrorType.VALIDATION),
    LOGO_URL_INVALID("VAL_LOGO_URL_INVALID", "Logo URL is invalid", ErrorType.VALIDATION),
    BANNER_URL_INVALID("VAL_BANNER_URL_INVALID", "Banner URL is invalid", ErrorType.VALIDATION),
    WEBSITE_URL_INVALID("VAL_WEBSITE_URL_INVALID", "Website URL is invalid", ErrorType.VALIDATION),
    ;

    private final String code;
    private final String defaultMessage;
    private final ErrorType errorType;

    private ErrorCode(String code, String message, ErrorType errorType) {
        this.code = code;
        this.defaultMessage = message;
        this.errorType = errorType;
    }

    public String getCode() {
        return code;
    }

    public String getDefaultMessage() {
        return defaultMessage;
    }

    public ErrorType getErrorType() {
        return errorType;
    }
}
