server:
  port: ${POST_SERVICE_PORT:9100}
  servlet:
    context-path: ${POST_CONTEXT_PATH:/posts}
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${POST_SERVICE_DB_URL}
    username: ${POST_SERVICE_DB_USERNAME}
    password: ${POST_SERVICE_DB_PASSWORD}
    hikari:
      maximum-pool-size: ${POST_SERVICE_DB_POOL_MAX_SIZE:20}
      minimum-idle: ${POST_SERVICE_DB_POOL_MIN_IDLE:5}
      connection-timeout: ${POST_SERVICE_DB_CONNECTION_TIMEOUT_MS:3000}
      validation-timeout: ${POST_SERVICE_DB_VALIDATION_TIMEOUT_MS:1000}
      max-lifetime: ${POST_SERVICE_DB_MAX_LIFETIME_MS:1800000}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

    api-key:
      current-service-key: ${POST_SERVICE_API_KEY}
      clients:
        file-service:
          url: ${POST_FILE_SERVICE_URL}
          api-key: ${POST_FILE_SERVICE_API_KEY}
          connect-timeout-ms: ${POST_FILE_SERVICE_CONNECT_TIMEOUT_MS:2000}
          read-timeout-ms: ${POST_FILE_SERVICE_READ_TIMEOUT_MS:3000}
        agri-catalog-service:
          url: ${POST_AGRI_CATALOG_SERVICE_URL}
          connect-timeout-ms: ${POST_AGRI_CATALOG_SERVICE_CONNECT_TIMEOUT_MS:2000}
          read-timeout-ms: ${POST_AGRI_CATALOG_SERVICE_READ_TIMEOUT_MS:3000}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

management:
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.nongthinh.post_service: INFO
    org.hibernate.SQL: WARN
