server:
  port: ${AGRI_CATALOG_SERVICE_PORT:9098}
  servlet:
    context-path: ${AGRI_CATALOG_CONTEXT_PATH:/agri-catalog}

spring:
  datasource:
    url: ${AGRI_CATALOG_SERVICE_DB_URL}
    username: ${AGRI_CATALOG_SERVICE_DB_USERNAME}
    password: ${AGRI_CATALOG_SERVICE_DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

    api-key:
      current-service-key: ${AGRI_CATALOG_SERVICE_API_KEY}
      clients:
        file-service:
          url: ${AGRI_CATALOG_FILE_SERVICE_URL}
          api-key: ${FILE_SERVICE_API_KEY}
        rice-disease-diagnosis-service:
          url: ${AGRI_CATALOG_DIAGNOSIS_SERVICE_URL}
          api-key: ${RICE_DISEASE_DIAGNOSIS_SERVICE_API_KEY}
