spring:
  application:
    name: auth-service

  profiles:
    default: dev

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${INTERNAL_CLIENT_CONNECT_TIMEOUT_MS:2000}
            readTimeout: ${INTERNAL_CLIENT_READ_TIMEOUT_MS:10000}
            loggerLevel: none

  security:
    oauth2:
      client:
        registration:
          keycloak:
            scope: openid
            authorization-grant-type: authorization_code

    api-key:
      header-name: X-API-KEY

  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

messaging:
  kafka:
    topics:
      brand-access-changed: ${KAFKA_TOPIC_BRAND_ACCESS_CHANGED:brand-access-changed}
      farmer-profile-creation-requested: ${KAFKA_TOPIC_FARMER_PROFILE_CREATION_REQUESTED:farmer-profile-creation-requested}
      admin-profile-creation-requested: ${KAFKA_TOPIC_ADMIN_PROFILE_CREATION_REQUESTED:admin-profile-creation-requested}
      brand-profile-creation-requested: ${KAFKA_TOPIC_BRAND_PROFILE_CREATION_REQUESTED:brand-profile-creation-requested}

server:
  forward-headers-strategy: framework

  servlet:
    session:
      cookie:
        path: /

cookie:
  http-only: true
  access-token-name: access_token
  refresh-token-name: refresh_token
  same-site: Lax
  access-path: /
  refresh-path: /

keycloak:
  scope: openid

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  observations:
    enabled: true
    http:
      server:
        requests:
          enabled: true

logging:
  level:
    root: INFO
    com.nongthinh: DEBUG
