create table email_template_purposes (
    id bigint generated by default as identity primary key,
    code varchar(100) not null unique,
    name varchar(255) not null,
    description text,
    system_defined boolean not null default false,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create table email_templates (
    id bigint generated by default as identity primary key,

    purpose_id bigint not null,

    name varchar(255) not null,
    description text,

    subject varchar(255) not null,

    html_content text,
    text_content text,

    is_active boolean not null default false,

    created_at timestamptz not null,
    updated_at timestamptz not null,

    foreign key (purpose_id)
        references email_template_purposes(id)
);

create unique index uq_email_templates_one_active_per_purpose
on email_templates (purpose_id)
where is_active = true;

create table email_template_variables (
    id bigint generated by default as identity primary key,
    purpose_id bigint not null,
    variable_name varchar(100) not null,
    description text,
    example_value varchar(255),
    is_required boolean not null default true,
    created_at timestamptz not null,
    updated_at timestamptz not null,

    foreign key (purpose_id)
        references email_template_purposes(id),

    unique (purpose_id, variable_name)
);
