create table email_histories (
    id bigint generated by default as identity primary key,
    user_id uuid,
    template_id bigint not null,
    purpose_id bigint not null,
    status varchar(20) not null,
    send_at timestamptz not null,

    foreign key (template_id)
        references email_templates(id),
    foreign key (purpose_id)
        references email_template_purposes(id)
);

create index idx_email_histories_user_id on email_histories (user_id);
create index idx_email_histories_template_id on email_histories (template_id);
create index idx_email_histories_purpose_id on email_histories (purpose_id);
create index idx_email_histories_status on email_histories (status);
create index idx_email_histories_send_at on email_histories (send_at);