server:
  port: ${PROFILE_SERVICE_PORT:9092}
  servlet:
    context-path: ${PROFILE_CONTEXT_PATH:/profile}

spring:
  datasource:
    url: ${PROFILE_SERVICE_DB_URL}
    username: ${PROFILE_SERVICE_DB_USERNAME}
    password: ${PROFILE_SERVICE_DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

    api-key:
      current-service-key: ${PROFILE_SERVICE_API_KEY}
      clients:
        location-service:
          url: ${PROFILE_LOCATION_SERVICE_URL}
          api-key: ${LOCATION_SERVICE_API_KEY}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
