spring:
  application:
    name: location-service

  profiles:
    default: dev

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true

  security:
    api-key:
      header-name: X-API-KEY

logging:
  level:
    root: INFO
    com.nongthinh: DEBUG

brand-access:
  profile-service:
    url: ${BRAND_ACCESS_PROFILE_SERVICE_URL:http://localhost:9092/profile}
    connect-timeout-ms: ${BRAND_ACCESS_CONNECT_TIMEOUT_MS:2000}
    read-timeout-ms: ${BRAND_ACCESS_READ_TIMEOUT_MS:3000}
