server:
  port: ${NOTIFICATION_SERVICE_PORT:9093}
  servlet:
    context-path: ${NOTIFICATION_CONTEXT_PATH:/notification}

spring:
  datasource:
    url: ${NOTIFICATION_SERVICE_DB_URL}
    username: ${NOTIFICATION_SERVICE_DB_USERNAME}
    password: ${NOTIFICATION_SERVICE_DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

    api-key:
      current-service-key: ${NOTIFICATION_SERVICE_API_KEY}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
